name: pictweak
description: A tool for image editing.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+3
  screenshot: ^1.3.0
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.2.0
  lottie: ^2.3.2
  google_fonts: 2.2.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  image_path: "assets/app_logo.png"
  android: true
  ios: false
